import { execFile } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { expect, test } from '@playwright/test';

const projectRoot = fileURLToPath(new URL('..', import.meta.url));
const execFileAsync = promisify(execFile);

test('About page states code and data license boundaries', async ({ page }) => {
  await page.goto('/?view=about');

  const licenses = page.locator('.about-page__license');
  await expect(licenses.nth(0)).toContainText(/METER\.AC-owned raw measurements.*CC0/);
  await expect(licenses.nth(0)).toContainText(/NIMH, NIGGG, EEA, OpenStreetMap.*source terms/);
  await expect(licenses.nth(1)).toContainText(/original project code.*Apache License 2\.0/);

  await expect(page.getByRole('link', { name: 'source repository' })).toHaveAttribute(
    'href',
    'https://github.com/meter-ac/my.meter.ac',
  );
  await expect(page.getByRole('link', { name: 'Apache License 2.0' })).toHaveAttribute('href', '/LICENSE.txt');
  await expect(page.getByRole('link', { name: 'project notice' })).toHaveAttribute('href', '/NOTICE.txt');
  await expect(page.getByRole('link', { name: 'third-party notices' })).toHaveAttribute(
    'href',
    '/THIRD_PARTY_NOTICES.txt',
  );
});

test('static legal artifacts are served', async ({ request }) => {
  const artifacts = [
    ['/LICENSE.txt', 'Apache License'],
    ['/NOTICE.txt', 'Copyright 2026 METER.AC contributors'],
    ['/THIRD_PARTY_NOTICES.txt', 'Hippocratic License 2.1'],
  ];

  for (const [path, expectedText] of artifacts) {
    const response = await request.get(path);
    expect(response.ok(), `${path} should be available`).toBe(true);
    expect(await response.text()).toContain(expectedText);
  }
});

test('root and public legal files stay byte-synchronized', async () => {
  const files = [
    ['LICENSE', 'public/LICENSE.txt'],
    ['NOTICE', 'public/NOTICE.txt'],
    ['THIRD_PARTY_NOTICES.md', 'public/THIRD_PARTY_NOTICES.txt'],
  ];

  for (const [rootPath, publicPath] of files) {
    const [rootContents, publicContents] = await Promise.all([
      readFile(`${projectRoot}/${rootPath}`),
      readFile(`${projectRoot}/${publicPath}`),
    ]);
    expect(publicContents.equals(rootContents), `${publicPath} should match ${rootPath}`).toBe(true);
  }
});

test('npm notices are version-independent and match dependency licenses', async () => {
  const notices = await readFile(`${projectRoot}/THIRD_PARTY_NOTICES.md`, 'utf8');
  const expectedNotices = [
    '`react-leaflet`: Copyright 2020 Paul Le Cam and contributors',
    '`@react-leaflet/core`: Copyright 2020 Paul Le Cam and contributors',
    'Leaflet is distributed under the BSD 2-Clause License',
    'React, ReactDOM, and Scheduler',
    'loose-envify:',
    'js-tokens:',
    'commander:',
    'TopoJSON Client is distributed under the ISC License',
    'runtime code generated by Vite and Rolldown',
    'Copyright (c) 2017 [these people]',
    'Copyright (c) 2020 Evan Wallace',
  ];

  for (const expectedNotice of expectedNotices) {
    expect(notices).toContain(expectedNotice);
  }

  const npmComponents = [
    'react-leaflet',
    '@react-leaflet/core',
    'Leaflet',
    'React',
    'ReactDOM',
    'Scheduler',
    'loose-envify',
    'js-tokens',
    'commander',
    'TopoJSON Client',
    'Vite',
    'Rolldown',
  ];

  for (const component of npmComponents) {
    const escapedComponent = component.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    expect(notices).not.toMatch(new RegExp(`${escapedComponent}[^\\n]*\\b\\d+\\.\\d+\\.\\d+\\b`, 'i'));
  }

  const expectedProductionPackageLicenses = {
    '@react-leaflet/core': 'Hippocratic-2.1',
    commander: 'MIT',
    'js-tokens': 'MIT',
    leaflet: 'BSD-2-Clause',
    'loose-envify': 'MIT',
    react: 'MIT',
    'react-dom': 'MIT',
    'react-leaflet': 'Hippocratic-2.1',
    scheduler: 'MIT',
    'topojson-client': 'ISC',
  };
  const expectedBuildPackageLicenses = {
    rolldown: 'MIT',
    vite: 'MIT',
  };
  const [productionLicenses, allLicenses] = await Promise.all([
    execFileAsync('pnpm', ['licenses', 'list', '--prod', '--json'], { cwd: projectRoot }),
    execFileAsync('pnpm', ['licenses', 'list', '--json'], { cwd: projectRoot }),
  ]);

  function indexLicensesByPackage(output) {
    const licensesByPackage = new Map();

    for (const [license, packages] of Object.entries(JSON.parse(output))) {
      for (const { name } of packages) {
        const packageLicenses = licensesByPackage.get(name) ?? new Set();
        packageLicenses.add(license);
        licensesByPackage.set(name, packageLicenses);
      }
    }

    return licensesByPackage;
  }

  const productionLicensesByPackage = indexLicensesByPackage(productionLicenses.stdout);
  expect([...productionLicensesByPackage.keys()].sort(), 'production dependency graph changed').toEqual(
    Object.keys(expectedProductionPackageLicenses).sort(),
  );

  for (const [packageName, expectedLicense] of Object.entries(expectedProductionPackageLicenses)) {
    const actualLicenses = [...(productionLicensesByPackage.get(packageName) ?? [])];
    expect(actualLicenses, `${packageName} license changed`).toEqual([expectedLicense]);
  }

  const allLicensesByPackage = indexLicensesByPackage(allLicenses.stdout);
  for (const [packageName, expectedLicense] of Object.entries(expectedBuildPackageLicenses)) {
    const actualLicenses = [...(allLicensesByPackage.get(packageName) ?? [])];
    expect(actualLicenses, `${packageName} license changed`).toEqual([expectedLicense]);
  }
});

test('map tiles use the current OSM host with an origin Referer', async ({ page }) => {
  const mapSource = await readFile(`${projectRoot}/src/components/StationMap.jsx`, 'utf8');
  expect(mapSource).toContain('url="https://tile.openstreetmap.org/{z}/{x}/{y}.png"');
  expect(mapSource).not.toMatch(/https:\/\/(?:\{s\}|[abc])\.tile\.openstreetmap\.org/);

  const tileRequestPromise = page.waitForRequest((request) => {
    const url = new URL(request.url());
    return url.hostname === 'tile.openstreetmap.org' && /\/\d+\/\d+\/\d+\.png$/.test(url.pathname);
  });

  await page.goto('/');
  const tileRequest = await tileRequestPromise;
  const tileUrl = new URL(tileRequest.url());
  const referer = tileRequest.headers().referer;

  expect(tileUrl.protocol).toBe('https:');
  expect(tileUrl.hostname).toBe('tile.openstreetmap.org');
  expect(referer).toBeTruthy();
  expect(new URL(referer).origin).toBe(new URL(page.url()).origin);
  expect(new URL(referer).pathname).toBe('/');
});
